export const products = [
	{
		id: 1,
		name: 'POWER WEEDER WM 450',
		image: 'agri-01.png',
		type: 'weeder',
		description: {
			engine: '3 HP -3600 RPM',
			engine_capacity: 149,
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '0.7 to 0.8',
			fuel: 'Petrol',
			fuel_tank_capacity: '1.2 litres',
			drive: 'Belt Drive',
			gear: '1 forward',
			weight: 37,
			no_of_blades: '3 pieces 4 group',
			working_width: 100,
			working_depth: 350,
		},
		additional_info: [
			'WM 450C Power Weeder is Petrol operated and is suitable for Intercultivation of Horticultural amd Floriculture crops of minimum distance planting. Weeder can be operated in minimum gap of 1.5 feet.',
			'450C is very compact attractive and gearless design allows the weeder to be operated at constant speed.',
			'450C weeder has oil bath air filter which prevents against dust and provides longer life.',
		],
		additional_attachments: null,
	},
	{
		id: 2,
		name: 'POWER WEEDER WM 500 DLX',
		image: 'agri-02.png',
		type: 'weeder',
		description: {
			engine: '6.5 HP -3600 RPM',
			engine_capacity: 196,
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '0.7 to 0.8',
			fuel: 'Petrol',
			fuel_tank_capacity: '3.0 Litres',
			drive: 'Belt Drive',
			gear: '2 Forward & 1 Reverse',
			weight: 60,
			no_of_blades: '24',
			working_width: 500 - 1000,
			working_depth: 150 - 300,
		},
		additional_info: [
			'WM 500 Power Weeder is belt operated secondary tillage equipment and is ideal for farmers for Intercultivation, Land preparation for sowing.',
			'Power Weeder has provided with newly diesigned Anti Mud start cover which prevents outer mud from entering the Air Filter which makes the weeder suitable for Muddy land tilling operation.',
			'Weeder comes with newly designed handle type drain plug on the carburettor which helps in easy maintanance and operation.',
			'Special Air filter with newly designed Inlet Pipe helps in 5% less fuel consumption. ',
		],
		additional_attachments: [
			'K1,2 and 3 type ridgers can be attached to this weeder for creating ditches and furrows.',
			'HTP sprayers can be attached for spraying operation.',
			'Garden Wheels can be attached during ditching operation.',
		],
	},
	{
		id: 3,
		name: 'POWER WEEDER WM 990',
		image: 'agri-03.png',
		images: [
			'/assets/product-images/WM 990/1.png',
			'/assets/product-images/WM 990/2.png',
			'/assets/product-images/WM 990/3.png',
			'/assets/product-images/WM 990/4.png',
		],
		type: 'weeder',
		description: {
			engine: '7 HP -3600 RPM',
			engine_capacity: 196,
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '0.7 to 0.8',
			fuel: 'Petrol',
			fuel_tank_capacity: '3.0 litres',
			drive: 'Gear  drive',
			gear: '2 Forward & 1 Reverse',
			weight: 53,
			no_of_blades: '24',
			working_width: 1000,
			working_depth: 100 - 150,
		},
		additional_info: [
			'WM 990 Power Weeder is gear operated secondary tillage equipment and is ideal for farmers for Intercultivation, Land preparation for sowing.',
			'Weeder has high economic efficiency, high power output and Low fuel consumption',
			'This weeder has opened clutch design which allows safety during operation and this design helps the weeder to stop once the hand is released from clutch.',
			'Weeder comes with newly designed handle type drain plug on the carburettor which helps in easy maintanance and operation.',
			'Power Weeder has provided with newly diesigned Anti Mud start cover which prevents outer mud from entering the Air Filter which makes the weeder suitable for Muddy land tilling operation. ',
			'Full protection fender allows the weeder to be well covered at all terminals.',
		],
		additional_attachments: [
			'K1,2 and 3 type ridgers can be attached to this weeder for creating ditches and furrows.',
			'HTP sprayers can be attached for spraying operation.',
			'Garden Wheels can be attached during ditching operation.',
			'Single Plough can be attached to this weeder for loosening of the soil and turning the soil for sowing operations.',
		],
	},
	{
		id: 4,
		name: 'POWER WEEDER WM 1100C',
		image: 'agri-04.png',
		images: [
			'/assets/product-images/WM 1100C WITH 6 HP GEAR BOX/Untitled design.png',
			'/assets/product-images/WM 1100C WITH 6 HP GEAR BOX/Untitled design (1).png',
			'/assets/product-images/WM 1100C WITH 6 HP GEAR BOX/Untitled design (2).png',
			'/assets/product-images/WM 1100C WITH 6 HP GEAR BOX/Untitled design (3).png',
		],
		type: 'weeder',
		description: {
			engine: '7 HP -3600 RPM',
			engine_capacity: 196,
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '0.7 to 0.8',
			fuel: 'Petrol',
			fuel_tank_capacity: '3.5 litres',
			drive: 'Gear  drive',
			gear: '2 Forward & 1 Reverse',
			weight: 105,
			no_of_blades: '32',
			working_width: 800 - 1100,
			working_depth: 150 - 300,
		},
		additional_info: [
			'WM 1100C Power Weeder is gear operated secondary tillage equipment and is ideal for farmers for Intercultivation, Land preparation for sowing.  Weeder comes with heavy duty gear box which helps in powerfull strength and is recommended for all tillage activities.',
			'Weeder has high economic efficiency, high power output and Low fuel consumption',
			'This weeder has opened clutch design which allows safety during operation and this design helps the weeder to stop once the hand is released from clutch.',
			'Weeder comes with newly designed handle type drain plug on the carburettor which helps in easy maintanance and operation.',
			'Multiple attachments can be used along with this weeder which allows the weeder to be Multi Purpose model.',
			'Elite series is available in this weeder segment.',
		],
		additional_attachments: [
			'K1,2 and 3 type ridgers can be attached to this weeder for creating ditches and furrows.',
			'HTP sprayers can be attached for spraying operation.',
			'Garden Wheels can be attached during ditching operation.',
			'Single Plough can be attached to this weeder for loosening of the soil and turning the soil for sowing operations.',
		],
	},
	{
		id: 5,
		name: 'POWER WEEDER WM 1000N/A',
		image: 'agri-05.png',
		type: 'weeder',
		description: {
			engine: '6 HP -3600 RPM',
			engine_capacity: 196,
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '0.7 to 0.8',
			fuel: 'Diesel',
			fuel_tank_capacity: '3.0 litres',
			drive: 'Gear  drive',
			gear: '2 Forward & 1 Reverse- High & Low gear shift',
			weight: 105,
			no_of_blades: '32',
			working_width: 800 - 1100,
			working_depth: 150 - 300,
		},
		additional_info: [
			'WM 1100A6 weeder is Diesel opeerated and is designed with both 3 speed and 6 speed Gearbox. This makes the weeder suitable for operaing with all the attachments such as sprayer, Back rotary and Ditcher attachments.',
			'Power Weeder has provided with newly diesigned Anti Mud start cover which prevents outer mud from entering the Air Filter which makes the weeder suitable for Muddy land tilling operation.',
			'This weeder has opened clutch design which allows safety during operation and this design helps the weeder to stop once the hand is released from clutch.',
			'Weeder comes with newly designed handle type drain plug on the carburettor which helps in easy maintanance and operation.',
			'Multiple attachments can be used along with this weeder which allows the weeder to be Multi Purpose model.',
			'This model is available with Self start kit which allows in easy starting of the weeder.',
		],
		additional_attachments: [
			'K1,2 and 3 type ridgers can be attached to this weeder for creating ditches and furrows.',
			'HTP sprayers can be attached for spraying operation.',
			'Garden Wheels can be attached during ditching operation.',
			'Single Plough can be attached to this weeder for loosening of the soil and turning the soil for sowing operations.',
			'Interlaced Paddy Wheel helps in Wet land cultivation.',
			'Water Pump can be attached for lifting of the water.',
		],
	},
	{
		id: 6,
		name: 'POWER WEEDER WM 1100C-6',
		image: 'agri-06.png',
		images: [
			'/assets/product-images/WM 1100C6 DIESEL POWER WEEDER/1.png',
			'/assets/product-images/WM 1100C6 DIESEL POWER WEEDER/2.png',
			'/assets/product-images/WM 1100C6 DIESEL POWER WEEDER/3.png',
		],
		type: 'weeder',
		description: {
			engine: '7.3 HP -3600 RPM',
			engine_capacity: 296,
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '0.7 to 0.8',
			fuel: 'Diesel',
			fuel_tank_capacity: '5.0 litres',
			drive: 'Gear  drive',
			gear: '2 Forward & 1 Reverse. High and Low Gear shift available',
			weight: 120,
			no_of_blades: '32',
			working_width: 800 - 1100,
			working_depth: 150 - 300,
		},
		additional_info: [
			'WM 1100C6 weeder is Diesel operated 9HP  and is designed with both 3 speed and 6 speed Gearbox. This makes the weeder suitable for operaing with all the attachments such as sprayer, Back rotary and Ditcher attachments.',
			'Power Weeder has provided with newly diesigned Anti Mud start cover which prevents outer mud from entering the Air Filter which makes the weeder suitable for Muddy land tilling operation.',
			'This weeder has opened clutch design which allows safety during operation and this design helps the weeder to stop once the hand is released from clutch.',
			'Weeder comes with newly designed handle type drain plug on the carburettor which helps in easy maintanance and operation.',
			'Multiple attachments can be used along with this weeder which allows the weeder to be Multi Purpose model.',
			'This model is available with Self start kit which allows in easy starting of the weeder.',
		],
		additional_attachments: [
			'Both Back rotary and Ditcher can be attached to the weeder as an additional attachment.',
			'K1,2 and 3 type ridgers can be attached to this weeder for creating ditches and furrows.',
			'HTP sprayers can be attached for spraying operation.',
			'Garden Wheels can be attached during ditching operation.',
			'Single Plough can be attached to this weeder for loosening of the soil and turning the soil for sowing operations.',
			'Interlaced Paddy Wheel helps in Wet land cultivation.',
			'Water Pump can be attached for lifting of the water.',
		],
	},
	{
		id: 7,
		name: 'POWER TILLER - MAIJO MAHAVEER 13HP',
		image: 'agri-08.png',
		images: [
			'/assets/product-images/MAHAVEER POWER TILLER/1.png',
			'/assets/product-images/MAHAVEER POWER TILLER/2.png',
			'/assets/product-images/MAHAVEER POWER TILLER/3.png',
			'/assets/product-images/MAHAVEER POWER TILLER/4.png',
			'/assets/product-images/MAHAVEER POWER TILLER/5.png',
			'/assets/product-images/MAHAVEER POWER TILLER/6.png',
			'/assets/product-images/MAHAVEER POWER TILLER/7.png',
			'/assets/product-images/MAHAVEER POWER TILLER/8.png',
		],
		type: 'tiller',
		description: {
			engine: '13HP -2400 RPM',
			engine_capacity: null,
			engine_type:
				'Single Cylinder/Horizontal/ 4 stroke- OHV/ direct injection/ water cooled',
			fuel_consumption: '190 gms/hp/hour',
			fuel: 'Diesel',
			fuel_tank_capacity: '11 litres',
			drive: 'Side drive',
			gear: '6 Forward & 2 Reverse',
			weight: 405,
			no_of_blades: '18',
			working_width: 600,
			working_depth: 150,
		},
		additional_info: [
			'Land tilling & leveling',
			'Wet land puddling',
			'In the PTO attachments can be attached for different applications like threshing, water pumping etc',
			'Goods Haulage',
		],
		additional_attachments: [
			'Leveller, Seed Drill,Reaper, Sprayer, Water Pump, Haulage,  Ridger, Cultivator 5 tyne',
			'Cage wheel for wetland land cultivation',
		],
	},
	{
		id: 8,
		name: 'POWER WEEDER WM 1100A6 DLX',
		image: 'agri-07.png',
		images: [
			'/assets/product-images/WM 1100C6 WITH BACKROTARY ATTACHMENT/Untitled design.png',
			'/assets/product-images/WM 1100C6 WITH BACKROTARY ATTACHMENT/Untitled design (1).png',
			'/assets/product-images/WM 1100C6 WITH BACKROTARY ATTACHMENT/Untitled design (2).png',
			'/assets/product-images/WM 1100C6 WITH BACKROTARY ATTACHMENT/Untitled design (3).png',
		],
		type: 'reaper',
		description: {
			engine: '6 HP -3600 RPM',
			engine_capacity: 289,
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '1.4',
			fuel: 'Diesel',
			fuel_tank_capacity: '3  Litres',
			drive: null,
			gear: '2 Forward & 1 Reverse.',
			weight: 168,
			no_of_blades: '8 set',
			working_width: 120,
			working_efficiency: 0.66,
		},
		additional_info: [
			'Diesel Operated Paddy reaper comes with Side Clutch mechanism which helps in Easy manuvering of the reaper.',
			'The crops are cut and placed to the RHS of the reaper.',
			'The reaper ensures less grain loss  in operation thus results  more productivity.',
		],
		additional_attachments: null,
	},
	{
		id: 9,
		name: 'BRUSH CUTTER - MAIJO BGJ 430',
		image: 'producta-1.png',
		type: 'brushCutter',
		description: {
			maximum_speed_of_gear_shaft: '7000/9000',
			engine_speed: 8000,
			gear_transmission_type: 'Automatic Centrifugal Clutch Spiral bevel Bear; Drive Shaft',
			idle_speed: '1500 + 50',
			reduction_ratio: '17:22',
			blade_rotation_direction: 'Counter-Clockwise (seen from top)',
			type_of_handle: 'Double Grip',
			engine_type: 'Air-cooled: 4 Stroke; Vertical Piston Value; Petrol Engine',
			displacement: '42 CC',
			engine: '2.10HP @ 6500 RPM',
			carburettor: 'Diaphragm-type',
			method_of_starting: 'Recoil type',
			fuel_used: 'Petrol and  2T-Oil (ratio 25:1) to be added separately',
			fuel_tank_capacity: 1.1,
			dry_weight: 4.2,
			length_of_main_pipe: 1500,
			length_of_drive_shaft: 1522,
			standard_blades:
				'Diamond shape 2teeth blade 1 no. 1 Nylon cutter and One number Circular 80T TCT Blade',
			crops: 'Paddy, Wheat, Maize, Mulberry, Sunflower, Grass, Plantain',
		},
		additional_info: [
			'Maijo Brush cutter BC 430 DLX is Back Pack model which makes the operation to be very user friendly. This Brush Cutter comes with Japanese Walbro carburetor & champion spark plug.  Also, the transmission pipe diameter is 28 mm makes it sturdy. The cutting speed and the torque is high in this machine there by one of the most preferred brush cutters by the profession bush cleaners & farmers.',
			'Features Back Pack Model Brush Cutter with 28 mm diameter transmission pipe',
			'With Walbro carburetor & Champion spark plug',
			'Comes with Nylon cuter, 2-teeth blade and 80 Teeth TCT Blade as stand accessory',
			'With full operator safety kit',
		],
		additional_attachments: null,
	},
	{
		id: 10,
		name: 'MAIJO FR 1821A',
		image: 'producta-2.png',
		type: 'sprayer',
		description: {
			engine: '2 in 1 Sprayer',
			chemical_tank_capacity: '16 Ltr',
			weight_of_the_sprayer: '7 kg',
			charging_duration: '8 hours',
			battery_power: '6 – 7 hours',
			nozzles: '3 nos.',
			additional_indicators: 'Voltmeter',
		},
		additional_info: [
			'George Maijo offers valuable products under Plant Protection category. To cater the demands of farmers Maijo is providing an excellent Battery Cum Manual operated Sprayer.',
			'This sprayer is a 2 in 1 model which comes with 16Ltr HDPE chemical tank and 12 Volts 8 amps Dry cell Battery.',
			'This sprayer is mainly used for spraying of Insectides, Fertilizers and Pesticides in all types of crops, Public sanitizing and household spraying.',
		],
		additional_attachments: null,
	},
	{
		id: 11,
		name: 'MAIJO REAPER 4S 1.2',
		image: 'producta-3.png',
		type: 'reaper',
		description: {
			engine_type: 'PETROL OPERATED, 4 STROKE, AIR COOLED',
			engine: '5.5 HP',
			cc: 289,
			fuel_consumption: '0.8L',
			gears: '1 FORWARD AND 1 REVERSE',
			blades: 24,
			weight: '110kg',
			area_coverage: '0.5 ACRE/HR',
			width_of_cut: '4 FEET',
			cutting_height: '3-3.5 INCH',
		},
		additional_info: [
			'Maijo 4S 1.2 Paddy Reaper is powered by 5.5 HP Petrol operated Engine and direct gear driving mechanism which eliminates the power loss caused during Pulley and Belt operation.',
			'The crops are cut and placed to the RHS of the reaper.',
			'The reaper ensures less grain loss  in operation thus results  more productivity.',
			'This model offers the low vibration and lesser crop loss during reaping operation which helps in maximum ROI for farmers.',
		],
		additional_attachments: null,
	},
	{
		id: 12,
		name: 'MAIJO REAPER MY 4G 120A',
		image: 'producta-6.png',
		type: 'reaper',
		description: {
			engine_type: 'Diesel OPERATED, 4 STROKE, AIR COOLED',
			hp: 6,
			cc: 289,
			fuel_consumption: '0.8L',
			gears: '1 FORWARD AND 1 REVERSE',
			blades: 24,
			weight: '168kg',
			area_coverage: '0.5 ACRE/HR',
			width_of_cut: '4 FEET',
			cutting_height: '3-3.5 INCH',
		},
		additional_info: [
			'Maijo MY 4G 120A Paddy Reaper is powered by 6 HP Diesel operated Engine and transmitted by Pulley and Belt operation.',
			'The crops are cut and placed to the RHS of the reaper.',
			'The reaper ensures less grain loss  in operation thus results  more productivity.',
		],
		additional_attachments: null,
	},
	{
		id: 13,
		name: 'MAIJO BC 520B DLX',
		image: 'producta-5.png',
		type: 'reaper',
		description: {
			maximum_speed_of_gear_shaft: '7000/9000',
			engine_speed: 8000,
			gear_transmission_type: 'Automatic Centrifugal Clutch Spiral bevel Bear; Drive Shaft',
			idle_speed: '1500 + 50',
			reduction_ratio: '17:22',
			blade_rotation_direction: 'Counter-Clockwise (seen from top)',
			type_of_handle: 'Double Grip',
			engine_type: 'Air-cooled: 4 Stroke; Vertical Piston Value; Petrol Engine',
			displacement: '52 CC',
			engine: '2.10HP @ 6500 RPM',
			carburettor: 'Diaphragm-type',
			method_of_starting: 'Recoil type',
			fuel_used: 'Petrol and  2T-Oil (ratio 25:1) to be added separately',
			fuel_tank_capacity: 1.1,
			dry_weight: 4.2,
			length_of_main_pipe: 1500,
			length_of_drive_shaft: 1522,
			standard_blades:
				'Diamond shape 2teeth blade 1 no. 1 Nylon cutter and One number Circular 80T TCT Blade',
			crops: 'Paddy, Wheat, Maize, Mulberry, Sunflower, Grass, Plantain',
		},
		additional_info: [
			'Maijo Brush cutter BC 430 Maijo Brush cutter BC 520 DLX  comes with Japanese Walbro carburetor & champion spark plug.  Also, the transmission pipe diameter is 28 mm makes it sturdy. The cutting speed and the torque is high in this machine there by one of the most preferred brush cutters by the profession bush cleaners & farmers.  This is enlisted in various Govt. subsidy programs.',
		],
		additional_attachments: null,
	},
	{
		id: 14,
		name: 'RICE TRANSPLANTER - MAIJO AP 40',
		image: 'producta-4.png',
		type: 'transplanter',
		description: {
			engine_type: 'Air-Cooled Petrol Engine & 3.6 HP',
			plating_rows: 4,
			plating_displacement: '3 - 4cm',
			space_between_rows: '30cm',
			travelling_speed: '1.3km/h',
			no_of_plants_in_a_hill: '3-5',
			no_of_hills: '27/30/33',
			space_between_hill: '12.6/15.7/20.2/23.3cm',
			power_transmission: 'Universal Joint Portable Shaft',
			engine: '3.6 HP',
			mode_of_transmission: 'Gear',
		},
		additional_info: [
			'The accuracy & speed of planting is very high in this machine compare to any other paddy transplanters of similar category. A very rugged and reliable gearbox makes it the most versatile paddy transplanter.',
			'All operating levers and switches are conveniently located within an easy reach.',
			'Adjustable Transplanting Factors such factors as Seedling Taking Quantity, Number of Hills, and Planting Depth are all adjustable to fit cultivation modality and field conditions.',
		],
		additional_attachments: null,
	},
]
