export const shopProducts = [
	{
		id: 1,
		name: 'BRUSH CUTTER - MAIJO BC 520B DLX  (SIDE PACK MODEL)',
		image: 'producta-5.png',
		type: 'BRUSH CUTTER',
		description: {
			engine: '2 HP -6500 RPM/ 52cc',
			engine_type: 'Vertical / 2 stroke, aircooled, single cylinder',
			fuel_consumption: '0.6 - 0.7',
			fuel: 'Petrol mixed with 2T oil (01:0.25 ratio)',
			cutting_operation: 'Sure tap with nylon rope & 2 teeth blade',
			weight: 4.2,
			price: '25,000',
			tax: 'Inclusive of 18% GST',
			delivery: 'Delivery in 3-5 business days',
		},
		additional_info: [
			'George Maijo is offering a high quality 52CC BC 520 DLX side pack brush cutter, which is helpful for trimming of Grass and cutting of small branches.',
			'BC 520B DLX is light is weight and easy to operate and is equipped with Walbro carburettor and Champion spark plug.',
			'It can also be used in harvesting of crops like Paddy with circular blades for small land holding capacity farmers.',
		],
		additional_attachments: [
			'Tool-kit',
			'Shoulder Belt',
			'Tap & Go',
			'Petrol-Oil Mixing Bottle.',
			'Eye glass.',
		],
	},
	{
		id: 2,
		name: 'BRUSH CUTTER - MAIJO BGJ 430 (BACK PACK MODEL)',
		image: 'producta-1.png',
		type: 'weeder',
		description: {
			engine: '2 HP -6500 RPM / 43cc',
			engine_type: 'Vertical / 2 stroke, aircooled, single cylinder',
			fuel_consumption: '0.6 - 0.7',
			fuel: 'Petrol mixed with 2T oil (01:0.25 ratio)',
			cutting_operation: 'Sure tap with nylon rope, 3 teeth blade & Cultivator attachment',
			weight: '4.5',
			price: '26,000',
			tax: 'Inclusive of 18% GST',
			delivery: 'Delivery in 3-5 business days',
		},
		additional_info: [
			'George Maijo is offering a reliable backpack model Brushcutter Maijo BGJ 430, which is easy to handle during operation ',
			'Maijo BGJ 430 helps in trimming of Grass in gardens, and also weeding attachment can be used for removal of weeds from agricultural fields.',
			'It can also be used in harvesting of crops like Paddy with circular blades for small land holding capacity farmers.',
		],
		additional_attachments: [
			'Tool-kit',
			'Shoulder Belt',
			'Tap & Go, Circular Blade and 2T blade',
			'Petrol-Oil Mixing Bottle.',
			'Eye glass.',
		],
	},
	{
		id: 3,
		name: 'POWER WEEDER WM 430',
		image: 'wm-430.png',
		type: 'weeder',
		description: {
			engine: '2 HP - 6500 RP',
			speed: 'Frictional Clutch',
			engine_type: 'Vertical / 2 stroke',
			fuel_consumption: '0.6 to 0.7',
			fuel: 'Petrol with 2T oil',
			fuel_tank_capacity: '1.2 litres',
			weight_in_KG: 18.2,
			no_of_blades: '4 group blades',
			weeding_depth: 'Upto 3 inches',
			price: '16,000',
			tax: 'Inclusive of 12% GST',
			delivery: 'Delivery in 3-5 business days',
		},
		additional_info: [
			'WM 430 is used for intercultivating, weeding in crops of minimum distance of less than 1 feet. ',
			'WM 430 Power Weeder should be used in land that has already been cultivated using rotavators or using power tillers.  ',
			'WM450 Power Weeder has to be used only in lands which has sufficient moisture of around 35 - 40%.',
			'These are secondary tillage implement and are not recommeded to be used in hard soils or land with stones. ',
		],
	},
	{
		id: 4,
		name: 'POWER WEEDER WM 450C',
		image: 'agri-01.png',
		type: 'weeder',
		description: {
			engine: '3 HP -3600 RPM',
			engine_capacity_in_CC: '149',
			engine_type: 'Vertical / 4 stroke',
			fuel_consumption: '0.7 to 0.8',
			fuel: 'Petrol',
			fuel_tank_capacity: '1.2 litres',
			drive: 'Belt drive',
			gear: '1 forward',
			weight_in_KG: 37,
			no_of_blades: '3 pieces 4 group',
			working_width: 100,
			working_depth: 350,
			price: '38,000',
			tax: 'Inclusive of 12% GST',
			delivery: 'Delivery in 3-5 business days',
		},
		additional_info: [
			'This weeder is used for intercultivation operation to remove weeds and uprooting grass effectively. 		',
			'WM 450C power weeder is specially designed for small land holding customers and also for customers who are practising house hold farming.',
			'450C is very compact attractive and gearless design allows the weeder to be operated at constant speed 		',
			'Its light weight makes it to be operated very easily.  ',
		],
	},
	{
		id: 5,
		name: 'MAIJO FR 1821A',
		image: 'producta-2.png',
		type: 'BATTERY SPRAYER',
		description: {
			engine: '2 in 1 Sprayer',
			chemical_tank_capacity: '16 litres',
			weight_in_KG: 7,
			charing_duration: '8 hours',
			spray_time_or_battery_power: '6-7 hours',
			number_of_nozzles: '3 nos',
			additional_indicators: 'voltmeter',
			tax: 'Inclusive of all taxes',
			delivery: 'Arriving soon',
		},
		additional_info: [
			'2 in 1 Model featuring both Manual and Battery options',
			'This sprayer which comes with 16Ltr HDPE chemical tank and 12 Volts 8 amps Dry cell Battery.  ',
			'Enduring Performance:	This sprayer is mainly used for spraying of Insectides, Fertilizers and Pesticides in all types of crops, Public sanitizing and household spraying. ',
			'Low Operating Cost and Low Maintenance Cost',
		],
	},
]
